//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPCMTest.WebService3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService3.IWebService3")]
    public interface IWebService3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/getLab3Results", ReplyAction="http://tempuri.org/IWebService3/getLab3ResultsResponse")]
        string getLab3Results(int patient_id, ref string test_results);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/getPrivacyPolicyArray", ReplyAction="http://tempuri.org/IWebService3/getPrivacyPolicyArrayResponse")]
        string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebService3Channel : KPCMTest.WebService3.IWebService3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3Client : System.ServiceModel.ClientBase<KPCMTest.WebService3.IWebService3>, KPCMTest.WebService3.IWebService3 {
        
        public WebService3Client() {
        }
        
        public WebService3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getLab3Results(int patient_id, ref string test_results) {
            return base.Channel.getLab3Results(patient_id, ref test_results);
        }
        
        public string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive) {
            return base.Channel.getPrivacyPolicyArray(WS_ID, Target_WS_ID, strTargetMethodName, ref gid, ref strIncentive);
        }
    }
}
