//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPCMTest.WebService4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService4.IWebService4")]
    public interface IWebService4 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService4/getLab4Results", ReplyAction="http://tempuri.org/IWebService4/getLab4ResultsResponse")]
        string getLab4Results(int patient_id, ref string test_results);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService4/getPrivacyPolicyArray", ReplyAction="http://tempuri.org/IWebService4/getPrivacyPolicyArrayResponse")]
        string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebService4Channel : KPCMTest.WebService4.IWebService4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService4Client : System.ServiceModel.ClientBase<KPCMTest.WebService4.IWebService4>, KPCMTest.WebService4.IWebService4 {
        
        public WebService4Client() {
        }
        
        public WebService4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getLab4Results(int patient_id, ref string test_results) {
            return base.Channel.getLab4Results(patient_id, ref test_results);
        }
        
        public string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive) {
            return base.Channel.getPrivacyPolicyArray(WS_ID, Target_WS_ID, strTargetMethodName, ref gid, ref strIncentive);
        }
    }
}
