//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPCMTest.WebService5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService5.IWebService5")]
    public interface IWebService5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService5/getLab5Results", ReplyAction="http://tempuri.org/IWebService5/getLab5ResultsResponse")]
        string getLab5Results(int patient_id, ref string test_results);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService5/getPrivacyPolicyArray", ReplyAction="http://tempuri.org/IWebService5/getPrivacyPolicyArrayResponse")]
        string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebService5Channel : KPCMTest.WebService5.IWebService5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService5Client : System.ServiceModel.ClientBase<KPCMTest.WebService5.IWebService5>, KPCMTest.WebService5.IWebService5 {
        
        public WebService5Client() {
        }
        
        public WebService5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getLab5Results(int patient_id, ref string test_results) {
            return base.Channel.getLab5Results(patient_id, ref test_results);
        }
        
        public string[][] getPrivacyPolicyArray(int WS_ID, int Target_WS_ID, string strTargetMethodName, ref System.Guid gid, ref string strIncentive) {
            return base.Channel.getPrivacyPolicyArray(WS_ID, Target_WS_ID, strTargetMethodName, ref gid, ref strIncentive);
        }
    }
}
