<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="http://localhost:2609/WebService3/Service.svc?xsd=xsd0" namespace="http://tempuri.org/" />
      <xsd:import schemaLocation="http://localhost:2609/WebService3/Service.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:2609/WebService3/Service.svc?xsd=xsd2" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IWebService3_getLab3Results_InputMessage">
    <wsdl:part name="parameters" element="tns:getLab3Results" />
  </wsdl:message>
  <wsdl:message name="IWebService3_getLab3Results_OutputMessage">
    <wsdl:part name="parameters" element="tns:getLab3ResultsResponse" />
  </wsdl:message>
  <wsdl:message name="IWebService3_getPrivacyPolicyArray_InputMessage">
    <wsdl:part name="parameters" element="tns:getPrivacyPolicyArray" />
  </wsdl:message>
  <wsdl:message name="IWebService3_getPrivacyPolicyArray_OutputMessage">
    <wsdl:part name="parameters" element="tns:getPrivacyPolicyArrayResponse" />
  </wsdl:message>
  <wsdl:portType name="IWebService3">
    <wsdl:operation name="getLab3Results">
      <wsdl:input wsaw:Action="http://tempuri.org/IWebService3/getLab3Results" message="tns:IWebService3_getLab3Results_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWebService3/getLab3ResultsResponse" message="tns:IWebService3_getLab3Results_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="getPrivacyPolicyArray">
      <wsdl:input wsaw:Action="http://tempuri.org/IWebService3/getPrivacyPolicyArray" message="tns:IWebService3_getPrivacyPolicyArray_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWebService3/getPrivacyPolicyArrayResponse" message="tns:IWebService3_getPrivacyPolicyArray_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IWebService3" type="tns:IWebService3">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="getLab3Results">
      <soap:operation soapAction="http://tempuri.org/IWebService3/getLab3Results" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getPrivacyPolicyArray">
      <soap:operation soapAction="http://tempuri.org/IWebService3/getPrivacyPolicyArray" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WS3_Implementation">
    <wsdl:port name="BasicHttpBinding_IWebService3" binding="tns:BasicHttpBinding_IWebService3">
      <soap:address location="http://localhost:2609/WebService3/Service.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
